ARG FEDORA=44
FROM registry.fedoraproject.org/fedora:${FEDORA}
RUN dnf -y --setopt=install_weak_deps=False install \
    gnome-shell gnome-extensions-app gjs libadwaita gtk4 \
    mesa-dri-drivers dbus-daemon dbus-tools \
    xorg-x11-server-Xvfb xauth python3 make \
    && dnf clean all
WORKDIR /work
